#!/usr/bin/env zsh


export SPACESHIP_PROMPT_SEPARATE_NEWLINE=true
export SPACESHIP_PROMPT_SEPARATE_LINE=true
export SPACESHIP_VI_MODE_SHOW=false
export SPACESHIP_USER_SHOW=always
export SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
export SPACESHIP_USER_PREFIX="╭─"
export SPACESHIP_CHAR_PREFIX="╰─"
export SPACESHIP_CHAR_SYMBOL="λ"
export SPACESHIP_CHAR_SUFFIX=" "